### ISSUE TITLE
Container keeps running after manual test stopping

### ISSUE THREAD

**Issue by venclov** [Jc2k/pytest-docker-tools#17]
In a scenario when test is manually stopped in the middle of execution, docker container, which is required for the test, is not removed. This then produces an error the next time test is run because port for the docker container in host machine is already allocated. I understand that this is an edge case, but is it possible to overcome this by doing some kind of clean up after shutting down the test or before running it?

**Comment by Jc2k** [comment]
I've noticed the same when e.g. doing Ctrl+C. Can you confirm thats what you are doing to manually stop the test?

Not really sure the best way forward TBH.

In terms of cleaning up afterwards, it is already trying to. But i guess pytest isn't running the fixture cleanup function. If pytest isn't going to call our cleanup code, what can we do?

In terms of cleaning up before, we could cover some of the cases sure but there are quite a few more variables in play. The advantage of cleaning up afterwards is we know exactly which containers we created, so we can delete those and do it safely. Running a cleanup before might mean i'm interfering with completely unrelated containers. I have used this plugin with xdist for example, and the cleanup would need to take care not to interfere with that - even when using parameterized tests.

If the docker API lets you tag containers (can't remember if thats a thing in Docker) then could use a autouse session fixture to delete them all when your test suite starts in a safe way, but i'd be reluctant to make it a default behaviour.

It doesn't solve the cleaning up problem, but i wanted to add: for my tests i use ephemeral ports for my tests so I never see the tests fail as you describe. From the README:

```python
apiserver = container(
    image='{apiserver_image.id}',
    ports={
        '8080/tcp': None,
    },
    dns=['{fakedns.ips.primary}']
)


@pytest.fixture
def apiclient(apiserver):
    port = apiserver.ports['8080/tcp'][0]
    return HTTPConnection(f'localhost:{port}')
```

The container definition says "map 8080/tcp from container to an ephemeral port on host". You can then retrieve what the ephemeral port actually is by looking at `apiserver.ports['8080/tcp'][0]` in your test. So at least you won't get test failures. Bonus, you can run your tests concurrently.

**Comment by venclov** [comment]
I am ussually use VS Code debugger to debug my tests and stop them in the middle of execution using "stop" button which probably does the same thing under the hood as Ctrl+C .

I agree with you on all of your points. We literally just kill the python process and pytest fixture cleanup isn't being executed. Docker API allows to add name to the container (tags are for images) and I can see that your wrapper supports it. I will try to come up with a code snippet in the following days which would use the name for cleanup before starting a new container and maybe it will be enough to solve this.

**Comment by Jc2k** [comment]
I think we can close this now. Let me know if there is anything else I can help with.
