### ISSUE TITLE
utils.tests_inside_container() not working

### ISSUE THREAD

**Issue by alexanderpetrenz** [Jc2k/pytest-docker-tools#20]
I'm working with the image python:3.8-slim on a Linux Host (Ubuntu Focal and Manjaro). I was wondering why when in the pipeline retrieving the container ip address results always in 127.0.0.1. It turned out that the function utils.tests_inside_container() is not working as intended. 

I did some testing with a bash session in such a container. tests_inside_container is evaluating the first line of `/proc/1/sched`.
In a container of that image the first line is contains `bash (1, #threads: 1)` and according to the short doc string shouldn't be the case.

@Jc2k What is your usual setup? Could you check if the current implementation is still working on your side?

I was searching a bit and it seems that there are well discussed approaches to implement this by evaluating /proc/self/cgroup. For a docker environment on Linux one could use:
```
def tests_in_container():
    path = "/proc/self/cgroup"
    if not os.path.isfile(path):
        return False
    with open(path) as f:
        for line in f:
            if re.match("\\d+:[\\w=]+:/docker(-[ce]e)?/\\w+", line):
                return True
        return False
```

Another more conventional approach was also discussed [here](https://stackoverflow.com/questions/43878953/how-does-one-detect-if-one-is-running-within-a-docker-container-within-python) suggests to pass some env variable into the container and evaluating it. However I guess this would not integrate that nicely. But maybe it could become some optional alternative.

Thanks
Alex

**Comment by alexanderpetrenz** [comment]
or maybe even simply 

```
def tests_in_container():
    path = "/proc/self/cgroup"
    if not os.path.isfile(path):
        return False
    with open(path) as f:
        for line in f:
            if "docker" in line:
                return True
        return False
```

**Comment by Jc2k** [comment]
I don't use this library that much now but I used to use Docker for Mac and Ubuntu 18.04 hosts with alpine containers. The Ubuntu VM was was running the tests via gitlab's docker runner. I used to build the images in one step, then test them, then deploy them. On my Mac, it would always run a fresh build rather than using the one from CI.

I can't remember what the function is supposed to do even to be honest. I'm on my phone right now but I'll have a look tomorrow and see if I can remind myself... If it was an optional thing there's a possibility I didn't ever actually use it as intended... 🤪

Reluctant to look for things containing the "docker" string now that fedora/red hats thing has a docker compatible API. Any idea if it's compatible with pod man?

**Comment by alexanderpetrenz** [comment]
Its not compatible. However the lib is called pytest-**docker**-tools :) Using podman with python:3.8-slim /proc/self/cgroup gives
```
12:devices:/user.slice
11:perf_event:/
10:freezer:/
9:memory:/user.slice/user-1000.slice/user@1000.service
8:blkio:/user.slice
7:hugetlb:/
6:pids:/user.slice/user-1000.slice/user@1000.service
5:cpuset:/
4:rdma:/
3:net_cls,net_prio:/
2:cpu,cpuacct:/user.slice
1:name=systemd:/user.slice/user-1000.slice/user@1000.service/app.slice/vte-spawn-a515359f-3532-4130-bcaa-91810e42d87c.scope/333f7fedad3533e13ca0b38c505edede89738bed77e12399b5d0bf78090252a1
0::/user.slice/user-1000.slice/user@1000.service/app.slice/vte-spawn-a515359f-3532-4130-bcaa-91810e42d87c.scope
```

Besides, there's also lxc, systemd-nspawn and I'm sure there's more of them.

In the end the most generic way could be using an environmental variable. But maybe the focus here may be only docker.

**Comment by Jc2k** [comment]
I read Podman has a docker compatible API and can run ci tasks with less privileges, apparently. I'm less interested in the others.

**Comment by Jc2k** [comment]
Here is some context about why this detection method stopped working: https://github.com/systemd/systemd/issues/8153

There's also some great discussion about how systemd intends to fix it in a related PR: https://github.com/systemd/systemd/pull/17902

For our purposes, the main thing is that `/.dockerenv` or `/run/.containerenv` exists. Lenart points out why it sucks, and I agree but if its good enough for systemd it's good enough for this.

So i'd take a PR that tests for the presence of either of those files.

**Comment by Jc2k** [comment]
#22 is now in release 1.0.1. Let me know if you have any problems.
