### ISSUE TITLE
build() custom Dockerfile file name support

### ISSUE THREAD

**Issue by diginc** [Jc2k/pytest-docker-tools#4]
Am I right in understanding the code only supports custom folder paths when building (`build(path='./folder')`) and not custom Dockerfile file names?

`Dockerfile_amd64, Dockerfile_armhf, etc` sharing the same added/copied file dependencies is my use case, so putting them in sub directories isn't ideal.

**Comment by Jc2k** [comment]
Off the top of my head it should pass through args to the underlying docker APIs. So looking [here](https://docker-py.readthedocs.io/en/stable/images.html#docker.models.images.ImageCollection.build), i'd expect it to take the `dockerfile` arg.

**Comment by Jc2k** [comment]
I didn't get the notify for the :+1: - but im going to take that as issue resolved and close this. Let me know if you have any other issues.
