### ISSUE TITLE
Parametrization of containers using arbitrary fixtures

### ISSUE THREAD

**Issue by thedrow** [Jc2k/pytest-docker-tools#46]
This is a follow-up question on #36.
Is it possible to use pytest's parametrization to generate multiple containers used in each test?
I'd like to be able to parameterize the configuration file's path to mount into the container.

**Comment by Jc2k** [comment]
Thats an interesting question; i honestly have no idea. What have you tried?

Under the hood everything "compiles down" to pytest fixtures, so if you can do it with fixtures you should be able to do it with pytest-docker-tools.

Looking at [this](https://hynek.me/til/parametrized-pytest-fixtures/), i'd expect you could make a parameterized fixture to get the path, which you can then refer to like normal in pytest-docker-tools:

```python
@pytest.fixture(name="config", params=("path1", "path2"))
def _config(request):
    return request.param

container(
    ...
    somevar="{config}",
    ...
)
```

I've not tried anything like this myself. Let me know how you get on.

**Comment by thedrow** [comment]
I haven't tried anything yet. I'll update you if I end up using this over testcontainers.
